version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Verify.Xunit
    versions:
    - 11.7.0
  - dependency-name: FluentValidation
    versions:
    - 10.0.4
  - dependency-name: FluentValidation.DependencyInjectionExtensions
    versions:
    - 10.0.4
  - dependency-name: GraphQL
    versions:
    - 4.0.0
    - 4.0.1
    - 4.0.2
    - 4.3.0
  - dependency-name: GraphQL.NewtonsoftJson
    versions:
    - 4.0.0
    - 4.0.1
    - 4.3.0
