image: Visual Studio 2017
build_script:
- ps: >-
    dotnet build src --configuration Release

    dotnet test src --configuration Release --no-build --no-restore
test: off
artifacts:
- path: nugets\**\*.nupkg