image: Visual Studio 2019 Preview
skip_commits:
  message: /doco|Merge pull request.*/
install:
- cmd: choco install dotnetcore-sdk --pre
build_script:
- ps: >-
    dotnet build src --configuration Release

    dotnet test src --configuration Release --no-build --no-restore
test: off
artifacts:
- path: nugets\**\*.nupkg